version: "3.8"

services:
  lokadb:
    image: postgres:latest
    container_name: lokadb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ~/.gandiwa/data/postgres/data:/var/lib/postgresql/data
    networks:
      - backend

  gandiwa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gandiwa
    image: gandiwa
    restart: unless-stopped
    tty: true
    depends_on:
      - lokadb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.gandiwa/data/logs:/app/gandiwa/logs
    networks:
      - backend

networks:
  backend:
    external: true

